{
 "title": "Raspberry Pi Exporter",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(rpi_throttled,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Under-voltage detected",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Arm frequency capped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Currently throttled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Soft temperature limit active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"4\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under-voltage has occurred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"16\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Arm frequency capping has occurred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"17\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throttling has occurred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"18\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Soft temperature limit has occurred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"$node\",bit=\"19\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "rpi_temperature{instance=~\"$node\"}",
     "legendFormat": "{{chip}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "rpi_volt{instance=~\"$node\"}",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Frequence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "rpi_freq{instance=~\"$node\"}",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rpi_mem{instance=~\"$node\"}",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  }
 ]
}